version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Change from true to false temporarily

formats:
  - pdf
  - htmlzip
  - epub

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
